remote_theme: pmarsceill/just-the-docs
title: Exchange Server Support Scripts
description: Exchange Server support scripts from Microsoft CSS
permalink: /:title/
aux_links:
  "CSS-Exchange on GitHub":
    - "//github.com/microsoft/CSS-Exchange"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/microsoft/CSS-Exchange" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Google Analytics
ga_tracking: G-W4DV3XCSNP
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings
